#!/usr/bin/env bun
/**
 * agent-context: builds .hermes.md, Hermes Agent's project context, from README_AI_AGENT.md + AGENTS.md.
 *
 *   bun scripts/agent-context.ts           write .hermes.md
 *   bun scripts/agent-context.ts --check   exit 1 if .hermes.md is missing or stale (part of agent:check)
 *
 * Why generated: Hermes loads exactly one project context file (first match wins:
 * .hermes.md → AGENTS.override.md → AGENTS.md → CLAUDE.md → .cursorrules) and does not expand
 * @imports, so the contract and the shared conventions must be inlined.
 * Spec: docs/agent-operations/hermes.md
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, '.hermes.md');
const SOURCES = ['README_AI_AGENT.md', 'AGENTS.md'];
const REQUIRED = new Set(['README_AI_AGENT.md']);
const SOFT_LIMIT = 20_000; // Hermes truncates context files above its cap, which is never below 20,000 characters

function build(): { content: string; missing: string[] } {
  const missing: string[] = [];
  const parts = [
    '<!-- GENERATED by scripts/agent-context.ts from README_AI_AGENT.md + AGENTS.md. Do not edit: run `bun run agent:context`. -->',
    '',
  ];
  for (const file of SOURCES) {
    const path = join(ROOT, file);
    if (!existsSync(path)) {
      missing.push(file);
      continue;
    }
    parts.push(`<!-- ===== ${file} ===== -->`, '', readFileSync(path, 'utf8').trim(), '');
  }
  return { content: parts.join('\n'), missing };
}

function main(): number {
  const check = process.argv.includes('--check');
  const { content, missing } = build();

  for (const file of missing) {
    const msg = `${file} not found`;
    if (REQUIRED.has(file)) {
      console.error(`✗ ${msg}`);
      return 1;
    }
    console.warn(`! ${msg}; .hermes.md will contain the contract only`);
  }
  if (content.length > SOFT_LIMIT) {
    console.warn(`! .hermes.md is ${content.length} characters; Hermes may truncate above ${SOFT_LIMIT}. Trim AGENTS.md.`);
  }

  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : null;
  if (check) {
    if (current === content) {
      console.log(`agent:context ok: .hermes.md is current (${content.length} characters)`);
      return 0;
    }
    console.error(`✗ .hermes.md is ${current === null ? 'missing' : 'stale'}: run \`bun run agent:context\``);
    return 1;
  }
  if (current === content) {
    console.log('agent:context: .hermes.md already current');
  } else {
    writeFileSync(OUT, content);
    console.log(`agent:context: wrote .hermes.md (${content.length} characters)`);
  }
  return 0;
}

process.exitCode = main();
