#!/usr/bin/env bun
/**
 * obsidian-sync: one-way generator, sources of truth → obsidian-out/
 *
 *   bun scripts/obsidian-sync.ts            regenerate once
 *   bun scripts/obsidian-sync.ts --watch    regenerate on every change (realtime board)
 *   bun scripts/obsidian-sync.ts --check    validate only; exit 1 on errors (pre-commit / CI)
 *
 * Sources: docs/list-task-project.md · agent-history/entries/*.json (schema: agent-history/schema.json)
 * Spec:    docs/integrated-obsidian-local.md
 * Deps:    bun add -d ajv ajv-formats
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, watch, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TASKS_FILE = join(ROOT, 'docs', 'list-task-project.md');
const HISTORY_DIR = join(ROOT, 'agent-history', 'entries');
const SCHEMA_FILE = join(ROOT, 'agent-history', 'schema.json');
const OUT = join(ROOT, 'obsidian-out');
const GENERATED = '%% generated by scripts/obsidian-sync.ts: edit the sources, not this file %%';

// ---------------------------------------------------------------- types & constants

type Status = 'backlog' | 'todo' | 'doing' | 'review' | 'blocked' | 'done';

type Task = {
  id: string;
  title: string;
  phase: string;
  phaseNo: string;
  status: Status;
  area: string;
  owner: string;
  depends: string[];
  accept: string;
  line: number;
};

type Check = 'pass' | 'fail' | 'skipped' | 'n/a';

type Entry = {
  id: string;
  task_ids: string[];
  agent: { name: string; model?: string; operator: string };
  session: { started_at: string; ended_at: string; branch?: string; commits?: string[] };
  intent: string;
  outcome: 'done' | 'partial' | 'blocked' | 'abandoned';
  summary: string;
  changes: { path: string; action: string; note?: string }[];
  decisions?: { decision: string; reason: string; alternatives?: string[] }[];
  verification: { typecheck: Check; lint: Check; build: Check; db_reset: Check; db_tests: Check; manual: string };
  migrations?: string[];
  dependencies_added?: { name: string; version: string; reason: string }[];
  contract_deviations?: { rule: string; why: string }[];
  risks?: string[];
  follow_ups?: { task_id?: string; note: string }[];
  human_review: { required: boolean; reason?: string };
  supersedes?: string;
};

const STATUSES: Status[] = ['backlog', 'todo', 'doing', 'review', 'blocked', 'done'];
const LANE: Record<Status, string> = {
  backlog: 'Backlog', todo: 'Todo', doing: 'Doing', review: 'Review', blocked: 'Blocked', done: 'Done',
};
const AREAS = new Set(['repo', 'docs', 'agent-ops', 'frontend', 'backend', 'db', 'integration', 'infra', 'security']);
const FIELDS = ['status', 'area', 'owner', 'depends', 'accept'];
const OWNER_RE = /^(unassigned|human|human:[a-z0-9._-]+|agent:[a-z0-9._-]+)$/;
const TASK_ID_RE = /^PSI-\d{3}$/;
const HEADING_RE = /^###\s+(PSI-\d{3})\s+[·:—-]\s+(.+?)\s*$/;
const FIELD_RE = /^-\s+(status|area|owner|depends|accept):\s*(.*)$/;
const PHASE_RE = /^##\s+(Phase\s+(\d+)\b.*)$/;
const FENCE_RE = /^\s*(```|~~~)/;

// ---------------------------------------------------------------- task list

function parseTasks(md: string): { tasks: Task[]; errors: string[] } {
  const tasks: Task[] = [];
  const errors: string[] = [];
  const seen = new Set<string>();
  const where = (line: number) => `docs/list-task-project.md:${line}`;
  let phase = '';
  let phaseNo = '';
  let inFence = false;
  let current: Task | null = null;
  let fieldsSeen = new Set<string>();

  const finish = () => {
    if (!current) return;
    for (const f of FIELDS) {
      if (!fieldsSeen.has(f)) errors.push(`${where(current.line)} ${current.id}: missing "${f}"`);
    }
    tasks.push(current);
    current = null;
    fieldsSeen = new Set();
  };

  md.split(/\r?\n/).forEach((raw, index) => {
    const lineNo = index + 1;
    const line = raw.trimEnd();

    if (FENCE_RE.test(line)) {
      inFence = !inFence;
      return;
    }
    if (inFence) return;

    if (/^##\s/.test(line)) {
      finish();
      const m = line.match(PHASE_RE);
      phase = m ? m[1].trim() : '';
      phaseNo = m ? m[2] : '';
      return;
    }

    if (/^###\s/.test(line)) {
      finish();
      const h = line.match(HEADING_RE);
      if (!h) {
        if (/PSI-/.test(line)) errors.push(`${where(lineNo)}: malformed task heading "${line}"`);
        return;
      }
      const [, id, title] = h;
      if (seen.has(id)) errors.push(`${where(lineNo)} ${id}: duplicate task id`);
      if (!phase) errors.push(`${where(lineNo)} ${id}: task is not under a "## Phase N" heading`);
      seen.add(id);
      current = {
        id, title, phase, phaseNo, status: 'backlog', area: '', owner: 'unassigned',
        depends: [], accept: '', line: lineNo,
      };
      return;
    }

    if (!current) return;
    const f = line.match(FIELD_RE);
    if (!f) return;
    const [, key, rawValue] = f;
    const value = rawValue.trim();
    fieldsSeen.add(key);

    switch (key) {
      case 'status':
        if ((STATUSES as string[]).includes(value)) current.status = value as Status;
        else errors.push(`${where(lineNo)} ${current.id}: unknown status "${value}"`);
        break;
      case 'area':
        if (AREAS.has(value)) current.area = value;
        else errors.push(`${where(lineNo)} ${current.id}: unknown area "${value}"`);
        break;
      case 'owner':
        if (OWNER_RE.test(value)) current.owner = value;
        else errors.push(`${where(lineNo)} ${current.id}: malformed owner "${value}"`);
        break;
      case 'depends':
        if (value === '' || value === '—' || value === '-') break;
        for (const dep of value.split(/[,\s]+/).filter(Boolean)) {
          if (TASK_ID_RE.test(dep)) current.depends.push(dep);
          else errors.push(`${where(lineNo)} ${current.id}: malformed dependency "${dep}"`);
        }
        break;
      case 'accept':
        current.accept = value;
        break;
    }
  });
  finish();

  const ids = new Set(tasks.map((t) => t.id));
  for (const t of tasks) {
    for (const d of t.depends) {
      if (!ids.has(d)) errors.push(`${where(t.line)} ${t.id}: depends on unknown task ${d}`);
      if (d === t.id) errors.push(`${where(t.line)} ${t.id}: depends on itself`);
    }
  }
  return { tasks, errors };
}

// ---------------------------------------------------------------- agent history

function loadEntries(taskIds: Set<string>): { entries: Entry[]; errors: string[] } {
  const entries: Entry[] = [];
  const errors: string[] = [];
  if (!existsSync(HISTORY_DIR)) return { entries, errors };

  const ajv = new Ajv2020({ allErrors: true, strict: false });
  addFormats(ajv);
  const validate = ajv.compile(JSON.parse(readFileSync(SCHEMA_FILE, 'utf8')));

  for (const file of readdirSync(HISTORY_DIR).filter((f) => f.endsWith('.json')).sort()) {
    const rel = `agent-history/entries/${file}`;
    let data: unknown;
    try {
      data = JSON.parse(readFileSync(join(HISTORY_DIR, file), 'utf8'));
    } catch (e) {
      errors.push(`${rel}: invalid JSON (${(e as Error).message})`);
      continue;
    }
    if (!validate(data)) {
      for (const err of validate.errors ?? []) errors.push(`${rel}: ${err.instancePath || '/'} ${err.message}`);
      continue;
    }
    const entry = data as Entry;
    if (`${entry.id}.json` !== file) {
      errors.push(`${rel}: file name must equal id ("${entry.id}.json")`);
      continue;
    }
    const unknown = entry.task_ids.filter((t) => !taskIds.has(t));
    if (unknown.length) {
      errors.push(`${rel}: unknown task id(s) ${unknown.join(', ')}`);
      continue;
    }
    entries.push(entry);
  }

  const ids = new Set(entries.map((e) => e.id));
  for (const e of entries) {
    if (e.supersedes && !ids.has(e.supersedes)) {
      errors.push(`agent-history/entries/${e.id}.json: supersedes unknown entry ${e.supersedes}`);
    }
  }
  entries.sort((a, b) => a.session.started_at.localeCompare(b.session.started_at));
  return { entries, errors };
}

// ---------------------------------------------------------------- formatting helpers

const yaml = (v: unknown) => JSON.stringify(v); // JSON scalars/arrays are valid YAML flow values
const oneLine = (s: string) => s.replace(/\s+/g, ' ').trim();
const cell = (s: string) => oneLine(s).replace(/\|/g, '\\|');
const taskLink = (id: string) => `[[tasks/${id}|${id}]]`;
const historyLink = (id: string, label: string) => `[[history/${id}|${label.replace(/[|\]]/g, ' ')}]]`;

const wib = (iso: string, opts: Intl.DateTimeFormatOptions) =>
  new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Jakarta', hour12: false, ...opts }).format(new Date(iso));
const dayWIB = (iso: string) =>
  new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Jakarta', year: 'numeric', month: '2-digit', day: '2-digit' })
    .format(new Date(iso));
const timeWIB = (iso: string) => wib(iso, { hour: '2-digit', minute: '2-digit' });
const stampWIB = (iso: string) => `${dayWIB(iso)} ${timeWIB(iso)} WIB`;

// ---------------------------------------------------------------- renderers

function renderBoard(tasks: Task[], runs: Map<string, Entry[]>): string {
  const out = ['---', '', 'kanban-plugin: board', '', '---', ''];
  for (const status of STATUSES) {
    out.push(`## ${LANE[status]}`, '');
    if (status === 'done') out.push('**Complete**');
    for (const t of tasks.filter((x) => x.status === status)) {
      const n = runs.get(t.id)?.length ?? 0;
      const parts = [`${taskLink(t.id)} ${oneLine(t.title)}`];
      if (t.owner !== 'unassigned') parts.push(t.owner);
      if (n) parts.push(`${n} run${n === 1 ? '' : 's'}`);
      const tags = [t.area && `#${t.area}`, t.phaseNo && `#phase-${t.phaseNo}`].filter(Boolean).join(' ');
      out.push(`- [${status === 'done' ? 'x' : ' '}] ${parts.join(' · ')}${tags ? ` ${tags}` : ''}`);
    }
    out.push('', '');
  }
  out.push('%% kanban:settings', '```', JSON.stringify({ 'kanban-plugin': 'board' }), '```', '%%', '');
  return out.join('\n');
}

function renderHome(tasks: Task[], entries: Entry[]): string {
  const count = (s: Status) => tasks.filter((t) => t.status === s).length;
  const out = [
    '# P3MD Social: project home', '', GENERATED, '',
    '[[Board]] · [[Agent Log]]', '',
    '## Status', '',
    `| ${STATUSES.map((s) => LANE[s]).join(' | ')} | Total |`,
    `|${STATUSES.map(() => '---').join('|')}|---|`,
    `| ${STATUSES.map((s) => count(s)).join(' | ')} | ${tasks.length} |`, '',
  ];

  const list = (title: string, items: string[], empty: string) => {
    out.push(`## ${title}`, '');
    out.push(...(items.length ? items : [empty]), '');
  };
  const taskLine = (t: Task) => `- ${taskLink(t.id)} ${oneLine(t.title)} · ${t.owner}`;

  list('Blocked', tasks.filter((t) => t.status === 'blocked').map(taskLine), '_Nothing blocked._');
  list('Doing', tasks.filter((t) => t.status === 'doing').map(taskLine), '_Nothing in progress._');
  list('Review', tasks.filter((t) => t.status === 'review').map(taskLine), '_Nothing waiting for review._');

  const superseded = new Set(entries.map((e) => e.supersedes).filter(Boolean));
  const needReview = entries
    .filter((e) => e.human_review.required && !superseded.has(e.id))
    .reverse()
    .map((e) => `- ${historyLink(e.id, `${stampWIB(e.session.started_at)} · ${e.agent.name} · ${e.task_ids.join(', ')}`)}` +
      `${e.human_review.reason ? `: ${oneLine(e.human_review.reason)}` : ''}`);
  list('AI sessions waiting for a human', needReview, '_None._');

  const latest = [...entries].reverse().slice(0, 10)
    .map((e) => `- ${stampWIB(e.session.started_at)} · ${e.agent.name} · ${e.task_ids.map(taskLink).join(', ')} · ` +
      `${e.outcome}: ${historyLink(e.id, oneLine(e.intent))}`);
  list('Latest AI sessions', latest, '_No sessions yet._');
  return out.join('\n');
}

function renderAgentLog(entries: Entry[]): string {
  const out = ['# Agent Log', '', GENERATED, '', 'Every AI session, newest first (times in WIB). Back to [[Home]].', ''];
  if (!entries.length) out.push('_No sessions yet._', '');
  let day = '';
  for (const e of [...entries].reverse()) {
    const d = dayWIB(e.session.started_at);
    if (d !== day) {
      out.push(`## ${d}`, '');
      day = d;
    }
    const flags = [e.human_review.required ? 'needs review' : '', e.supersedes ? `supersedes ${e.supersedes}` : '']
      .filter(Boolean).join(', ');
    out.push(
      `- ${timeWIB(e.session.started_at)} · **${e.agent.name}** · ${e.task_ids.map(taskLink).join(', ')} · ` +
      `${e.outcome}${flags ? ` (${flags})` : ''}: ${historyLink(e.id, oneLine(e.intent))}`,
    );
  }
  out.push('');
  return out.join('\n');
}

function renderTask(t: Task, runs: Entry[], blocks: string[]): string {
  const out = [
    '---',
    `id: ${yaml(t.id)}`,
    `title: ${yaml(t.title)}`,
    `status: ${yaml(t.status)}`,
    `phase: ${yaml(t.phase)}`,
    `area: ${yaml(t.area)}`,
    `owner: ${yaml(t.owner)}`,
    `depends: ${yaml(t.depends)}`,
    `runs: ${runs.length}`,
    '---',
    `# ${t.id} · ${oneLine(t.title)}`, '', GENERATED, '',
    `**Status:** ${t.status} · **Area:** ${t.area} · **Owner:** ${t.owner} · **Phase:** ${t.phase}`, '',
    `**Accept:** ${t.accept || '_missing_'}`, '',
    `**Depends on:** ${t.depends.length ? t.depends.map(taskLink).join(', ') : '—'}`, '',
    `**Unblocks:** ${blocks.length ? blocks.map(taskLink).join(', ') : '—'}`, '',
    '## AI sessions', '',
  ];
  if (!runs.length) out.push('_None yet._');
  for (const e of runs) {
    out.push(`- ${stampWIB(e.session.started_at)} · ${e.agent.name} · ${e.outcome}: ${historyLink(e.id, oneLine(e.intent))}`);
  }
  out.push('', `Source: \`docs/list-task-project.md\` line ${t.line} · [[Board]]`, '');
  return out.join('\n');
}

function renderEntry(e: Entry): string {
  const out = [
    '---',
    `id: ${yaml(e.id)}`,
    `tasks: ${yaml(e.task_ids)}`,
    `agent: ${yaml(e.agent.name)}`,
    ...(e.agent.model ? [`model: ${yaml(e.agent.model)}`] : []),
    `operator: ${yaml(e.agent.operator)}`,
    `outcome: ${yaml(e.outcome)}`,
    `started: ${yaml(e.session.started_at)}`,
    `ended: ${yaml(e.session.ended_at)}`,
    `human_review: ${e.human_review.required}`,
    ...(e.supersedes ? [`supersedes: ${yaml(e.supersedes)}`] : []),
    '---',
    `# ${oneLine(e.intent)}`, '', GENERATED, '',
    `**Tasks:** ${e.task_ids.map(taskLink).join(', ')} · **Agent:** ${e.agent.name}` +
      `${e.agent.model ? ` (${e.agent.model})` : ''} · **Operator:** ${e.agent.operator} · **Outcome:** ${e.outcome}`, '',
    `**Session:** ${stampWIB(e.session.started_at)} → ${stampWIB(e.session.ended_at)}` +
      `${e.session.branch ? ` · branch \`${e.session.branch}\`` : ''}` +
      `${e.session.commits?.length ? ` · commits ${e.session.commits.map((c) => `\`${c}\``).join(', ')}` : ''}`, '',
    `**Human review:** ${e.human_review.required ? `required${e.human_review.reason ? `: ${oneLine(e.human_review.reason)}` : ''}` : 'not required'}`, '',
  ];
  if (e.supersedes) out.push(`**Supersedes:** ${historyLink(e.supersedes, e.supersedes)}`, '');

  out.push('## Summary', '', e.summary.trim(), '');

  out.push('## Changes', '');
  if (e.changes.length) {
    out.push('| Path | Action | Note |', '|---|---|---|');
    for (const c of e.changes) out.push(`| \`${cell(c.path)}\` | ${c.action} | ${cell(c.note ?? '')} |`);
  } else {
    out.push('_No files changed._');
  }
  out.push('');

  if (e.decisions?.length) {
    out.push('## Decisions', '');
    for (const d of e.decisions) {
      out.push(`- **${oneLine(d.decision)}**: ${oneLine(d.reason)}` +
        `${d.alternatives?.length ? ` (alternatives: ${d.alternatives.map(oneLine).join('; ')})` : ''}`);
    }
    out.push('');
  }

  const v = e.verification;
  out.push('## Verification', '', '| Check | Result |', '|---|---|',
    `| typecheck | ${v.typecheck} |`, `| lint | ${v.lint} |`, `| build | ${v.build} |`,
    `| db reset | ${v.db_reset} |`, `| db tests | ${v.db_tests} |`, '', `Manual: ${oneLine(v.manual)}`, '');

  const bullets = (title: string, items: string[] | undefined) => {
    if (!items?.length) return;
    out.push(`## ${title}`, '', ...items.map((i) => `- ${i}`), '');
  };
  bullets('Migrations', e.migrations?.map((m) => `\`${m}\``));
  bullets('Dependencies added', e.dependencies_added?.map((d) => `\`${d.name}@${d.version}\`: ${oneLine(d.reason)}`));
  bullets('Contract deviations', e.contract_deviations?.map((d) => `**${d.rule}**: ${oneLine(d.why)}`));
  bullets('Risks', e.risks?.map(oneLine));
  bullets('Follow-ups', e.follow_ups?.map((f) =>
    `${f.task_id && f.task_id !== 'NEW' ? taskLink(f.task_id) : 'NEW'}: ${oneLine(f.note)}`));

  out.push(`Source: \`agent-history/entries/${e.id}.json\` · [[Agent Log]]`, '');
  return out.join('\n');
}

// ---------------------------------------------------------------- vault writer

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) return false;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  return true;
}

/** Regenerates Board/Home/Agent Log/tasks/history plus read-only mirrors of docs/, README_AI_AGENT.md and graph/GRAPH_REPORT.md. Never touches README.md, .obsidian/ or architecture/. */
function writeVault(tasks: Task[], entries: Entry[]): number {
  const runs = new Map<string, Entry[]>();
  for (const e of entries) for (const t of e.task_ids) runs.set(t, [...(runs.get(t) ?? []), e]);
  const unblocks = new Map<string, string[]>();
  for (const t of tasks) for (const d of t.depends) unblocks.set(d, [...(unblocks.get(d) ?? []), t.id]);

  const files = new Map<string, string>();
  files.set('Board.md', renderBoard(tasks, runs));
  files.set('Home.md', renderHome(tasks, entries));
  files.set('Agent Log.md', renderAgentLog(entries));
  for (const t of tasks) files.set(`tasks/${t.id}.md`, renderTask(t, runs.get(t.id) ?? [], unblocks.get(t.id) ?? []));
  for (const e of entries) files.set(`history/${e.id}.md`, renderEntry(e));

  // Read-only mirrors so the whole project is browsable in the vault. Relative links keep working
  // because the folder layout matches the repo. README.md is skipped: the vault has its own.
  const mirror = (srcAbs: string, rel: string) => files.set(rel, readFileSync(srcAbs, 'utf8'));
  const walk = (dirRel: string) => {
    for (const d of readdirSync(join(ROOT, dirRel), { withFileTypes: true })) {
      const rel = `${dirRel}/${d.name}`;
      if (d.isDirectory()) { if (d.name !== '_archive') walk(rel); }
      else if (d.name.endsWith('.md')) mirror(join(ROOT, rel), rel);
    }
  };
  walk('docs');
  mirror(join(ROOT, 'README_AI_AGENT.md'), 'README_AI_AGENT.md');
  const report = join(ROOT, 'graphify-out', 'GRAPH_REPORT.md');
  if (existsSync(report)) mirror(report, 'graph/GRAPH_REPORT.md');

  let written = 0;
  for (const [rel, content] of files) if (writeIfChanged(join(OUT, rel), content)) written++;

  for (const dir of ['tasks', 'history', 'docs']) {
    const prune = (rel: string) => {
      if (!existsSync(join(OUT, rel))) return;
      for (const d of readdirSync(join(OUT, rel), { withFileTypes: true })) {
        const p = `${rel}/${d.name}`;
        if (d.isDirectory()) prune(p);
        else if (!files.has(p)) { rmSync(join(OUT, p), { force: true }); written++; }
      }
    };
    prune(dir);
  }
  return written;
}

// ---------------------------------------------------------------- main

const plural = (n: number, one: string, many = `${one}s`) => `${n} ${n === 1 ? one : many}`;

function run(mode: 'sync' | 'check', reason = ''): number {
  if (!existsSync(TASKS_FILE)) {
    console.error(`✗ missing ${TASKS_FILE}`);
    return 1;
  }
  const { tasks, errors: taskErrors } = parseTasks(readFileSync(TASKS_FILE, 'utf8'));
  const { entries, errors: entryErrors } = loadEntries(new Set(tasks.map((t) => t.id)));
  const errors = [...taskErrors, ...entryErrors];
  for (const e of errors) console.error(`✗ ${e}`);

  if (mode === 'check') {
    console.log(errors.length
      ? `agent:check failed: ${plural(errors.length, 'error')}`
      : `agent:check ok: ${plural(tasks.length, 'task')}, ${plural(entries.length, 'history entry', 'history entries')}`);
    return errors.length ? 1 : 0;
  }

  const written = writeVault(tasks, entries);
  console.log(`obsidian-sync${reason ? ` (${reason})` : ''}: ${plural(tasks.length, 'task')}, ` +
    `${plural(entries.length, 'session')}, ${plural(written, 'file')} updated` +
    `${errors.length ? `, ${plural(errors.length, 'problem')}: invalid items skipped` : ''}`);
  return 0;
}

function startWatch() {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const schedule = (why: string) => {
    clearTimeout(timer);
    timer = setTimeout(() => run('sync', why), 300);
  };
  mkdirSync(HISTORY_DIR, { recursive: true });
  // Watch directories, not files: editors often save by replacing the file.
  watch(dirname(TASKS_FILE), (_event, name) => {
    if (!name || String(name) === 'list-task-project.md') schedule('task list changed');
  });
  watch(HISTORY_DIR, (_event, name) => {
    if (!name || String(name).endsWith('.json')) schedule('history changed');
  });
  console.log('watching docs/list-task-project.md and agent-history/entries/ (Ctrl+C to stop)');
}

const args = process.argv.slice(2);
if (args.includes('--check')) {
  process.exitCode = run('check');
} else {
  process.exitCode = run('sync');
  if (args.includes('--watch')) startWatch();
}
